01-numpy.html
01-numpy.md
02-func.html
02-func.md
03-loop.html
03-loop.md
04-cond.html
04-cond.md
05-defensive.html
05-defensive.md
06-cmdline.html
06-cmdline.md
07-errors.html
07-errors.md

This change seems sensible for both reading the input markdown, and the rendering as HTML.
Assuming there is not something in the template which deals with this (and my change is not needed), then I would guess this fix will be needed on all the other recently migrated lessons (and the migration script may need tweaking).
Update: Looking at a few of the other lessons with R and Python (by eye), I did not find any more unescaped inequalities.

Unescape the less than and greater than inequalities

---

06-cmdline.md

The formatting for an example has a syntax error which generates incorrect output.

fix format for an example

---

05-defensive.md

Maybe a bit pedantic but the assertion condition  (n>=0) and the error message (Data should only contain positive values) do not match. 
It has to be either 
1. "n>=0" and "Data should only contain non-negative values" or 
2. "n>0" and "Data should only contain positive values". 
I think the latter is better, and requesting a change. Thanks

Corrected the assertion example

---

08-cmdline.html
08-cmdline.md

At the moment the command line lesson (`08-cmdline.html`) begins by calling python scripts from within the IPython notebook (using `%run script.py` or `!ipython script.py`) and then about half way through the lesson it switches to calling scripts from the command line itself (i.e. `$ python script.py`). This is very confusing for learners and instructors, so I'm proposing that we just use the command line from beginning to end (i.e. don't even open an IPython notebook for this lesson - just teach it entirely from the command line). 
This PR also fixes some little things towards the end of the lesson because no reference was made to `readings-05.py` or `readings-06.py` in the lesson notes.

Use command line throughout whole command line lesson

---

01-numpy.md
fig/python-operations-across-axes.svg

Fixing link the glossary term "library" from the lesson one page to the reference page.
Also removed potentially demotivating word "simple".
For the Operations across axes figure, I moved "average across axis 1" to the left because the "1" was being cut off.

Fixing link to `library` and other small fixes

---

01-numpy.md

There appears to have been a mistake in a including the challenges, as there was an extra:
"
>
> Plot scaling: why do all of our plots stop just short of the upper end of our graph?
"
in the first challenge. This is marked as its own challenge further down.

Removed repeated challenge

---

01-numpy.md
08-cmdline.md
code/readings-01.py
code/readings-02.py
code/readings-03.py
code/readings-04.py
code/readings-05.py
code/readings-06.py
reference.md

It's not worth introducing extra syntax just because folks might see
this in the wild.  As Greg said in 181e4635 (Starting to write
instructor's guide, 2015-02-15):
> In order to teach that, we must teach people a little about the
> mechanics of manipulating data with lists and file I/O so that their
> functions can do things they actually care about.  Our teaching
> order tries to show practical uses of every idea as soon as it is
> introduced; instructors should resist the temptation to explain the
> "other 90%" of the language as well.

Drop 'import ... as ...' syntax

---

05-cond.md

In this lesson there is an example that uses a function "def sign(num)" to illustrate some decision making capability. I don't know if this material has been reordered recently, but given that function definitions do not appear until the next lesson, I would argue that this be removed and just shown as a simple block of code that prints whether a number is -ve or +ve. I have suggested a potential replacement.

Removal for function (too early in lesson program)

---

01-numpy.md
09-errors.md
instructors.md

As per the discussion in #61, I added a pointer to why we're not using aliasing in this lesson to the `instructors.md` file. I put this in a Frequently Argued Issues (FAI) section, which I stole from @jdblischak (thanks for the idea!)
In grepping to make sure we're not aliasing imports anywhere in this lesson, I noticed that we do `from ... import` in `09-errors.md`, so I took out that syntax there as well. We still do this in `10-supplementary.md`, but it's explained there, and supplementary material, so I left it in.

Import cleanup

---

07-errors.md

in the Errors and Exceptions lesson.
I chose to keep the KeyError in the first challenge, because it is
a common thing to run into an exception that you've never heard of
before; students should have no problems answering the 6 questions
in the challenge despite not seeing a KeyError before. If anything,
it makes this challenge a bit cleaner, as we're mostly asking for
generic answers rather that should be the same regardless of the
error type.
I think this is the last minor fix necessary for 5.3. IMO!

Removed the rest of the KeyError references

---

08-cmdline.md

I've made a couple of minor edits to the challenges in `08-cmdline.md`:
* For the addition/subtraction lesson I've changed it so `arith.py` takes the word `addition`or `subtraction` as an input argument and not `+` or `-`, because the use of the symbols always creates a lot of unnecessary confusion
* There was a typo in one of the challenges where it told people to edit `count-stdin.py` when it should have said `readings.py`

Minor edits to challenges in 08-cmdline.md

---

01-numpy.md
04-files.md

This PR:
* Corrects a number of typos in `01-numpy.md` relating to the use of `matplotlib.pyplot`
* Removes the use of abbreviated library names (`np` and `plt`) in `04-files.md`
* Adds a callout to `01-numpy.md` about `% matplotlib inline`

Matplotlib fixes

---

03-lists.md

added a short section to the lists lesson warning against modifying
lists in place when two or more variables are pointing to the same list.
It may be worth including a sticky note figure for this point? I think it is a worthwhile addition to the lesson as this point cost me several hours of bugfixing when learning, and we have explicitly talked about the opposite behaviour in lesson 1. 
Apologies for the slowness of this pull request.

adding problems with modifying lists in place

---

03-lists.md

Related to #48
The output of the print statements in `python-novice-inflammation/03-lists.md`
is not currently shown for the last three code blocks. This pull request adds the output
to the `.md` file

DOC: maintains consistency in print statements 03-lists.md

---

02-loop.md

The mention of the pow function confuses people so that they think
they are supposed to use the pow function in their solution.
Here I've made the exercise more explicit by specifically telling
the students to use multiplication.
(I don't think the purpose of the exercise is to test whether students
remember that exponentiation is the same as multiplication.)

Make exponentiation loop exercise more explicit

---

01-numpy.md
03-lists.md
04-files.md
06-func.md
07-errors.md
10-cmdline.md
instructors.md

Note that this is a PR on the `py3k` branch.
I did a runthrough of the Python 3 lessons after merging @rgaiacs's PR to clean up any loose ends. After making these changes, the lesson runs properly for me in Python 3.
Often, these changes are just noticing when Python 3 gives different outputs than Python 2 and updating accordingly, and a few spots where we still had print statement (these were added after #142 was made).
One odd thing is that in Python 3, the list returned by `glob` isn't sorted. I'm not sure if this is also true in Python 2, but to be sure that the output is correct, I added `sorted` calls.
Another somewhat large change is that the exception classes are changed in Python 3; importantly, there's no longer a base IOError. Instead, the specific IOErrors are separated out. …

Minor updates for Python 3 compatibility

---

instructors.md

Solutions to programming exercises in `instructors.md` were still using Python 2 `print` syntax.

Fixing print statements in instructors.md

---

instructors.md

I'm not fully sure, but it appears that you have to have an empty line preceding and following an enumeration to have it properly convert in Jekyll. (This is slightly different from Github's Markdown rendering.)

Insert empty line to restore bullet point list formatting.

---

05-cond.md

The first conditional statement in "Checking our data" has
```python
if data.min(axis=0)[0] == 0 and data.max(axis=0)[20] == 20:
print('Suspicious looking maxima')
```
But the sections after "let's test that out" use
```python
if data.max(axis=0)[0] == 0 and data.max(axis=0)[20] == 20:
print('Suspicious looking maxima')
```
which seems to be the intended test. This pull request changes the first conditional statement to match the other two.

change data.min to data.max in Checking our Data section of 05-cond.md

---

06-func.md

Add missing `>` which lead to improper formatting.
Before:
After:

Fix formatting for python division example

---

03-lists.md

The generated HTML doesn't display 226--229 as a code block. It looks like pandoc requires a blank line before code blocks, but Github's builtin markdown renderer doesn't... Standards!

Add blank line to fix code block formatting

---

06-func.md

I think referring to the size of indents at this point could cause confusion. Given that it's not the first time we refer to indents, a reader might think that there is something about functions in particular that means that means they should be indented by four spaces. Also, this is already better dealt with in lesson 7.

Remove reference to size of indent

---

07-errors.md

Without this change, it could be interpreted to mean that using the "read" flag instead of the "write" flag can cause a `FileNotFoundError`, whereas it's a different type of error entirely.

Clarify expression of error types

---

10-cmdline.md

Changed explanation.
The original explanation "If `action` isn’t one of the three recognized flags, the program loads each file but does nothing with it (because none of the branches in the conditional match). Silent failures like this are always hard to debug." is incorrect.
$ python readings-04.py --blah test.txt
will throw exception as `values` is not defined through one of the flags
However,
$ python readings-04.py test.txt
$ python readings-04.py --max
will run and this produce a silent failure.
We only get a silent failure if we do not specify at least two additional arguments on the command-line, one for the **flag** and one for the **filename**, but only one, the program will not throw an exception but will run. It assumes that the file list is empty, as `sys.argv[1]` will be …

Lesson 10:-cmdline Explanation for silent failure is wrong for readings-04.py. 

---

03-lists.md
04-files.md

In the nested lists example (in 03-lists.md), the nested list created is 
```
x = [['pepper', 'zucchini', 'onion'],
['cabbage', 'lettuce', 'garlic'],
['apple', 'pear', 'banana']]
```
but in the outputs the second item of the first list is indicated as 'lettuce', e.g. print([x[0]])
was 
```
[['pepper', 'lettuce', 'onion']]
```
fixed that to `['pepper', 'zucchini', 'onion']` on line 136 and 144

changed 'lettuce' to 'zucchini' in 03-lists.md

---

05-cond.md

There was a typo in the link to the "in-place-operators" anchor tag.
Link now points to the anchor tag correctly and therefore will take users to the right term in the glossary.

Fixed broken link

---

index.md

Command `ipython notebook ` is deprecated, replaced with `jupyter notebook`.

Update Notebook command

---

07-errors.html
07-errors.md
10-cmdline.html
10-cmdline.md
index.html
index.md
instructors.html
instructors.md

The version of `ipython` installed with Anaconda (ipython 4.1.2 at time of writing) prints a deprecation message (see below) when `ipython notebook` is run.  Updating our materials to use `jupyter notebook` instead, the command to use going forward.
```
$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
```

Replace "ipython notebook" (deprecated) with "jupyter notebook"

---

05-cond.md
reference.md

Previous versions used ipythonblocks and tuples, mostly when teaching conditionals. I'm removing mentions to them in the code, as we are not using ipythonblocks anymore and tuples only mentioned in one challenge.
This fixes #262, but leaves untouched the entry for tuples in the glossary.

Remove mentions to ipythonblocks and tuples

---

07-errors.md

The print function is used in a different way in 07-errors.md compared
to all other parts of the lesson. This has been changed.

consistent use of print function

---

01-numpy.md
05-cond.md

It replaces links to SVG files with links with respective PNGs. This solves the problem with differences of rendering of SVGs on different platforms and browsers (mainly related to fonts - see #270 and #271).

link PNGs instead of SVGs (closes #270 and #271)

---

01-numpy.md

Made a quick note about the object. tab completion feature in IPython and ? help function. I found this to be helpful in the classes in letting them know how they can fend for themselves more quickly with a feature that they might otherwise not find.

Added callout for way to find methods in IPython

---

01-numpy.md

The argument "that’s simpler for computers to do" is not credible.
Compilers and interpreters can easily handle an offset of one.
The choice of index base is made with human convenience in mind.

Better explanation for base-0 indexing

---

01-numpy.md

Illustrates one of the differences between NumPy and MATLAB/intuition. Depending on the way you slice something, you may get back a 1D (N,) or 2D (Nx1) array, which can cause weird errors if you aren't expecting it.

Added challenge to 01-numpy.md regarding slicing a vector vs an array

---

01-numpy.md
04-files.md
05-cond.md
06-func.md
10-cmdline.md
discussion.md
instructors.md
reference.md

Most methods on NumPy arrays also have an equivalent NumPy function that takes the array as input. I have noticed that many novice programmers prefer functions (which have a pretty clear input-output relationship) to methods (which have an implicit input). This PR changes all instances of calling methods on arrays to calling the equivalent NumPy function instead. I tried to simplify the explanation in `01-numpy.md` as well, which hopefully does not significantly affect the flow of the prose.
This PR came out of one of the discussion sessions (apologies, I don't remember who brought this up -- if it was you, let me know and I'll add you to the commit message :) )

Prefer functions over methods.

---

01-numpy.md

Add a few lines to find out the type of elements (e.g floats, ints) in numpy arrays after mentioning `shape` and attributes of an array.

Finding type of elements of a numpy array

---

01-numpy.md

"load" and "import" are used interchangeably in 01-numpy. This PR replace all instances of 'load' with 'import' for consistency. It also adds some explanation what it means to import a library (=open).

use 'import' a library instead of 'load'

---

_episodes/06-func.md

The switcheroo example in the functions episode had all of the possible answers on one line and designated with a, b, c, d, unlike the other examples of 1, 2, 3, 4. This was also confusing as the variables in the example are a and b. I updated the formatting of the question and possible answers. I also added the solution with an explanation of why that is the correct answer. (SWC instructor training qualification)

Update switcheroo example

---

index.md

This needs to be a relative link to setup, not absolute.

BUG: Fix broken link to setup

---

_episodes/02-loop.md

Fixes one of the items in Issue #287:
[02-loops] Collection is not ordered - use sequence instead of collection.
Replaced three instances of the word 'collection' with the word 'sequence.'

Replace 'collection' with 'sequence' in for-loop explanation

---

_episodes/08-defensive.md

At the end of the defensive programming lesson it says that an important rule of programming is to *always initialize from data*. In the solution to the final challenge of that lesson the highest and lowest value are initialized using `numpy.inf`. I've changed this so they are initialized from the data instead.

Fix final defensive programming challenge so it initializes from data

---

_episodes/03-lists.md
_episodes/05-cond.md

This addresses two points raised in https://github.com/swcarpentry/python-novice-inflammation/issues/287:
- It renames the title of one of the exercises to make it clearer and not mention tuples
- It removes the same exercise from lesson 5 (this must have been added accidentally since it is not relevant to that lesson)
There are still some mentions of tuples scattered in a few places in the notes - should these be removed too?

Minor cleanup related to mentions of tuples

---

_episodes/07-errors.md

I agree with the reporter.
Since the only errors that are mentioned are IndexErrors it makes sense to just call it Index Errors.
If at some point other errors regarding containers are added, we might want to call it Container Errors or something like that.

Fix issue #267

---

_episodes/02-loop.md

The characters in a word were described in two different ways here (in L140 and L141, the characters were described as variables in a collection, and in L149, the word was described as the variable).
I have changed the wording on lines 140 and 141 to be a little less confusing.  Open to suggestions for different wording, but I think it should be consistent.

wording adjusted for consistency in description of loop operation

---

_episodes/09-debugging.md

"use to test oracles" -> "use test oracles"

Fix typo on 09-debugging.md

---

_episodes/02-loop.md

For the "What's in a name?" callout block in lesson 2, the block was
not being rendered as a callout. This change fixes that formatting.

Fix callout formatting instruction in loops lesson.

---

_episodes/03-lists.md

> right, left = left, right
> "...we pack right and left into a tuple and then unpack it again into left
> and right."
This example for variable value swapping introduces three new concepts:
1. the tuple data type
2. special tuple syntax, omitting parentheses
3. container unpacking in an assignment
I think using a list is much clearer, and only introduces the concept of
container unpacking.
right, left = [left, right]

Use list instead of tuple in variable swapping exercise

---

_episodes/08-defensive.md

This commit fixes the line numbers referred to in the normalize_rectangle function of defensive programming were incorrect. My guess is the comment line was added later, and the line numbers were not updated.
Also added the line numbers for the post-conditions "The post-conditions on lines 17 and 18...". I thought this would clarify to learners which assertions were preconditions and which ones were post-conditions.

Fixed incorrect line numbers in 08-defensive.md

---

CONTRIBUTING.md

In CONTRIBUTING.md, there were two "FIXME" placeholders sitting in two links under Point 1 of  "Where to Contribute," instead of "python-novice-inflammation." Fixed.

Fixed CONTRIBUTING.md links 

---

_episodes/02-loop.md
_episodes/05-cond.md

We use box color to help learners to know which block they should **type** and run on their Jupyter Notebook or Python console. This pull request fix the color of one block that learners should not type.

Fix code block color

---

setup.md

When I unzip the python-novice-inflammation-code.zip file, it becomes a folder called python-novice-inflammation-code NOT (as indicated in the instructions) 'code.' Perhaps this could be fixed at the zipped file level, rather than by changing these instructions.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be …

Wording Change & Folder Name

---

CONTRIBUTING.md

This contribution is for instructor training.
-----------------------------------------------
In the CONTRIBUTING.md file, the links to this repository's "issues" and "master link" are broken. At the bottom of the markdown file, the two global links were defined as:
[issues]: https://github.com/swcarpentry/FIXME/issues/
[repo]: https://github.com/swcarpentry/FIXME/
To fix the broken links, the "FIXME" is replaced by the name of the repository:
[issues]: https://github.com/swcarpentry/python-novice-inflammation/issues/
[repo]: https://github.com/swcarpentry/python-novice-inflammation/

Fix the links [issues] and [repo] in CONTRIBUTING.md

---

_episodes/01-numpy.md

As reported in #400, most of the links to the glossary in 01-numpy were pointing to an old location. This PR updates all the links to the correct location.

Fix reference links

---

_episodes/01-numpy.md

The output of the `%whos` magic shows that the `numpy` module is loaded, while that actually only happens in the next section.  In this branch, I've deleted the output line that shows the module.

Fix output of %whos, numpy is not imported yet

---

_episodes/01-numpy.md

Change the name of the variable for the standard deviation plot example, so that it reflects what it contains.

Use a descriptive name for sd plot example

---

_episodes/08-defensive.md

---
Currently the normalize_rectangle function is somewhat confusing. Putting an example of the input format, as described in the text, in the docstring is both an example of good programming practice and makes the exercise more straightforward.
---

Add input example to normalize_rectangle

---

_episodes/07-errors.md

Based on info from this site: https://daringfireball.net/projects/markdown/syntax#html
I have replaced the markdown code block with html code (copied the html source from http://swcarpentry.github.io/python-novice-inflammation/07-errors/ and added a tab). The indentation has been increased on all lines as html tabs are 8 characters wide, not 4 and it is hard to change the html tabs to 4 characters.

Issue #221 - add tab to 'Tabs and Spaces' example

---

_episodes/01-numpy.md

Fixed the filename of the input from data/inflammation-01.csv to inflammation-01.csv to be consistent with the rest of the content in this session, assuming that the data/ is the working directory (this also avoids conflicts between unix- and windows-style path descriptions).

Fixed filename in "Moving Plots Around" challange

---

_episodes/05-cond.md

The print string for the if statement was coded to 53, and can cause confusion in my opinion. I changed to concatenate the num variable which is consistent with the rest of the lesson. I also updated some double-quote string to single-quote strings for better consistency.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can …

Remove hard coded print string and changed quotes

---

_episodes/08-defensive.md

Us an en dash instead of a figure dash in order to represent a numeric range.

Update 08-defensive.md — en dash for numeric range

---

_episodes/01-numpy.md

Array is not a built-in function and hasn't been imported specifically. Changed to call by numpy.array to prevent NameError

edited explanation of numpy.diff

---

_episodes/03-lists.md

Change variable 'mySalsa' to 'my_salsa' for PEP 8 compliance.

---

README.md

In response to #498, adds line breaks in the README.md and _episodes/03-lists.md files to decrease the number of lines with over 100 characters.
I did not address the over-length lines linking the buttons in the README, nor the code snippet for `list_for_slicing` in the episode, since modifying those lines -- to the best of my understanding -- would alter the rendering.
Thank you for your work maintaining these lessons !

[ENH] README.md line length

---

_episodes/03-lists.md

Helps to address #498, following up on #565 !
Changes proposed:
- Breaks up long lines (i.e., > 100 characters) in _episodes/03-lists.md

[ENH] Add line breaks in _episodes/03-lists

---

_episodes/01-numpy.md

In preparing for an instructor training test I noticed a few minor issues in the first episode; a few typos and a few cases where `weight_kg` is printed as an integer when it was actually reassigned as a floating point value before the print. That's probably a drawback of hard-coding the results of the prints in as regular text.

01-numpy.md: minor code result / content fixes

---

_episodes/01-numpy.md

Part about sticky notes should've really been added as a callout box that gives an alternative interpretation of variables.

01-numpy.md: move notes about sticky notes to callout box

---

_episodes/10-cmdline.md

Most of the changes have to do with long lines in the 10th episode.
On line 57 I also change `readings_04.py` to `readings_06.py` to make episode in sync with file names. 
The problem with the filename was reported by @mrawls.

10-cmdline: fix long lines and more

---

README.md

#495 Improve README.md
Based [swcarpentry/r-novice-inflammation]([https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/README.md) README
- put maintainers in a list, easier to read
- add a short introduction
- add links to other language versions of lesson (R and MATLAB)

README.md: add 'About the Lesson' section

---

_episodes/06-func.md

* Fix long lines
* remove long output of 'help(numpy.loadtxt)'
* use Anaconda 3 (and Python 3.6) for one of the examples

06-func.md: fix long lines and other fixes

---

_episodes/01-numpy.md

1. `automatically` seems to be unnecessary as the main point is that `weight_lb` is not updated.
2. `languages like` seems to be not necessary either as at this point learners know that we're talking about Python and no need to generalize.
3. Removed two extra blank lines...

01-numpy.md: simplify wording

---

_episodes/01-numpy.md

I think we intended to make all calls `numpy.max(x)` instead of `x.max()`, to reduce cognitive load for learners.

Change x.max() to numpy.max(x)

---

_episodes/01-numpy.md

Fixes episode/lesson term use in episode 1, following on from issue #602. Using 1 PR per episode as requested.

Clarify lesson-episode term (Episode 1)

---

_episodes/01-numpy.md

I propose to remove two places where there's ambiguity between IPython and Jupyter notebook.
In line 605: tab completion works both in IPython (command line) and in the IPython/Jupyter notebook.
Most importantly, line 734 caused a lot of confusion in a recent workshop I was helping at, where 3-4 participants thought using "%matplotlib inline" was needed for all IPython uses (it's appropriate only when using the Notebook). And using it in the command line IPython meant the interpreter could not find the backend, and plotted nothing.
It is unlikely new users today will find anything called "IPython notebook", since it's now called "Jupyter notebook", so I removed the ambiguity.

Resolve iPython vs. Jupyter Notebook ambiguity

---

_episodes/09-debugging.md

as a way to find the commit that introduced an issue in "Version Control Revisited".

Mention also `bisect` command

---

_episodes/08-defensive.md

Change `low` and `high` variables to `left` and `right` respectively since that's what is normally used to call the interval endpoints.
Also I think `lowest` and `highest` are quite confusing since they are actually calculated as `max` and `min` respectively. I have therefore changed these to `max_left` and `min_right`.
I've also added an additional `assert` to justify the:
```
if not ranges:
return None
```
check in the final exercise solution.
Finally, I've removed an unused `import numpy` in the final exercise.

Rename variables in `range_overlap` function

---

README.md

As initially suggested in #495, and broken out from PR #610, I've added a table of episodes to the README. Perhaps we could discuss whether this is useful. I do feel that the README could do more to explain what the repository is for (such as my suggestion of adding a little info on the SWC and the goal of the lesson to the introduction as I had in #610).

Adds a table of episodes to README

---

fig/README.md

Adding notes about cleaning up SVG files.

fig/README.md: add notes about cleaning up SVG files

---

_episodes/02-lists.md
_episodes/03-loop.md
_extras/extra_exercises.md

I added lines 293-318, which were deleted from the 02-lists lesson, to the end of _extras/extra_exercises.md.

adding for loop exercise to _extras/extra_exercises.md

---

_episodes/03-lists.md

At present, negative indexing is used in lesson 3 of `Programming with Python` before it is defined. This PR adds a short explanation of negative indexing before it is first used. The later explanation of negative indexing (in the section on slicing) now uses reminder of the earlier explanation as a hint.

Add explanation of negative indexing before first usage

---

_episodes/02-loop.md

The chunk was labeled python, but the code written was descriptive and not actually executable python code. This can be confusing for newcomers. The proposed change is to simply put in a placeholder comment, to keep everything labeled python as real python.

Update code chunk for basic form of for loop

---

_episodes/03-loop.md
_extras/extra_exercises.md

Removing all looping over strings in the loops episode of the lists-loops episode swap branch to avoid adding in an extra concept to discuss that might not add enough value for learners. Going to read over this again to check for typos and clarity before marking it ready for review (set as a draft for now). Let me know if there's additional changes that could be made. Thanks!
In reference to #496

[lists-loops branch] replace string loops with lists

---

setup.md

Two changes:
1. add `index.html` to permalink.
Currently, the link to the setup page works correctly online, when the site is served (locally), but not when it is built with `jekyll build`. Addint `index.html` should solve the last problem.
2. Explicitly mention that one has to install Anaconda as the first step of the setup.

setup.md: fix header and add instructions to install Anaconda

---

_episodes/07-errors.md

Obvious typo: occurr -> occur
My editor also stripped an empty whitespace at the end of another line which is not ideal (I prefer to make clean commits) but I'm going to leave it the way it is because I can never justify submitting a separate PR to remove unnecessary whitespace.

07-errors.md: typo

---

_episodes/03-lists.md

This is a suggestion to resolve #669 . Since `del` is a statement, not a method/function, the unexplained difference in syntax may be confusing to learners. Using `pop` shows that you can remove a value from a list and make use of the value that was removed.

03-lists.md: Use `pop()` for consistency of method over statement

---

_episodes/06-func.md
reference.md

This is meant to help issue #489.

Stressed that functions do not need to return a value. Issue #489.

---

_episodes/01-numpy.md

The note explaining that libraries can be imported with a shorter name seems better placed at the point in the lesson where library imports are introduced.
When reviewing the lesson for the first time in preparation for teaching, when describing how to import I was surprised this wasn't introduced as pretty much every code example I see usual has import numpy as np, so I immediately thought this was a gap in the lesson.  But then I did find this note further down in the lesson which says everything that is needed, but it strikes me as rather tangential in its current position, but I think would be much more relevant in the position I've suggested as at this point import has just been used for the first time.

Moved note on importing numpy as np

---

setup.md

According to [this table in the lesson example](https://carpentries.github.io/lesson-example/06-style-guide/index.html#keyboard-key)
we ought to use `Return` instead of `Enter`.

setup.md: Return not Enter

---

_episodes/08-defensive.md

The time required for exercises in this episode is I think between 5 and 10 minutes. Of course, times required for all episodes' exercises really depends upon the experience of participants. I'm sure I'm not saying anything you don't know. :)

Update 08-defensive.md: exercise time

---

_episodes/08-defensive.md

According to the style guide we have to use `<kbd></kbd>`...

08-defensive.md: fix styling of keyboard shortcuts

---

_episodes/02-loop.md

change `.python` to `.language-python`
For some reason, `.python` code block specification is not rendered the way `.language-python` is. So, "fixing" this until we figure out what to do with it.
@annefou, please review and merge if you agree with the changes -- the space was deleted by my text editor.

02-loop.md: fix Python code block specification

---

_episodes/06-func.md

The function on line 152 could arguably be called visualize(). If such a change is made, other references to analyze() would need to be changed. Just a thought.

Update 06-func.md: visualize() vs analyze()

---

code/readings_03.py

Issue #675, notes that in lesson 10, when it points to `readings_03.py`, the code shown in the lesson does not match the code that's in the `readings_03.py` file. The lesson shows the line `numpy.mean(data, axis=1)` while the file has `data.mean(axis=1)`. From a comment on the issue, it was recommended to change the file to match the lesson, since they should show the same code and SWC would prefer to teach functions over methods. This PR applies that change and fixes #675

Change mean method in readings_03.py

---

_episodes/08-defensive.md

Resolves #731.
One downside of this is that the cell numbers reported in the error messages no longer match the others in the same episode. I'm not sure how important that is, though (students will see different numbers anyway), and I don't think they followed on exactly from previous episodes to start with. I hope that's fine.

Update line numbers in normalize_rectangle

---

_episodes/01-numpy.md

As per issue 716, remove reference to `%matplotlib inline` as it is no longer required.

01-numpy.md: Remove paragraph about '%matplotlib inline' magic

---

_episodes/06-func.md

requested [here](https://github.com/swcarpentry/python-novice-inflammation/pull/729/files#r342135330)

06-func.md: typo, function was renamed, not docstring

---

_episodes/06-func.md

I feel that using the word "simple" can be a bit dismissive. I don't think we can assume that novices would agree that the tests outlined would be simple for them to come up with when they're first starting out with Python. I think this can be reworded to convey a similar meaning without being as dismissive.

Remove the word "simple" from 06-func.md

---

_episodes/06-func.md

You will also see that some of the information was incorrect due to
multiple update. The function used to be called `center` and to return
a list instead of a numpy array. So the help and example were incorrect.
The use of the numpy standard is a good practice; as most projects use
it. Even if we don't expect users to remember it; at least they are made
aware that there is standard and can look for it.
This also mirror the documentation style of loadtxt that is seen later
in the lesson.
And finally sphinx can understand numpydoc and generate nice HTML pages.
So all in all I believe this is a nice detail to add to the lesson.
Please delete this line and the text below before submitting your contribution

Update some docstring sections to use numpy standard.

---

_episodes/03-loop.md

The Output block in this exercise contains two assignments to the variable y, which neither looks like an Output nor does it follow from the preceding Python block when run.
I believe the first assignment to y was intended to be part of the Python block, and I also believe the intent was to print the value of y, which is 97, instead of assigning 97 to it in the Output block.
This commit does the following:
- moves the first y assignment from the Output block into the Python block
- adds a print(y) statement to the end of the Python block
- removes the assignment from the y = 97 line, so that the Output block matches the output of the edited Python block when it is run.
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this …

Fix 'Computing the Value of a Polynomial' exercise

---

_episodes/11-cmdline.md

`stdout` was referred to in the keypoint, but not mentioned in the text of episode 11. Hence the removal.
closes #764

11-cmdline.md: remove keypoint referring to stdout

---

_episodes/02-numpy.md

The previous explanation implies that Python will always print 1.0 as "1." when there's nothing after the decimal point. However, this is specific to numpy. For example, the statement "print(1.0)" will print "1.0" and not "1.". I changed the description to refer to a numpy array instead of Python in general. I also clarified the space saved was on the screen (rather than in memory, for example).

Clarification of 1.0 v 1.

---

_episodes/02-numpy.md

Using a variable called `npdiff` to hold an array is highly confusing,
given that the function to be learned here is called {numpy,np}.diff().
Also, stress that the array returned by `diff()` is shorter by one.

02-numpy: clarify numpy.diff() part

---

_episodes/04-loop.md

Fixing small typo: `asterix -> asterisk`.

Fixing small typo

---

_episodes/03-matplotlib.md

The previous text did not mention, in a first moment, that the average was related to the patients' inflammation. Adding the word `inflammation` makes the text clearer.

Clarifying info on average inflammation

---

_episodes/02-numpy.md

This is a pull request for issue https://github.com/swcarpentry/python-novice-inflammation/issues/780
Change the lesson example from using random data to using patient 3 week 1 data from the included inflammation dataset. Variable name has also been changed to be more descriptive of the data it contains.
Question in the 2D array `numpy.diff` example added introduction to `axis` argument.

Updating 02-numpy numpy.diff example to use patient data

---

_episodes/01-intro.md

Variables as Sticky Notes now has a detailed content: ../fig/python-sticky-note-variables-01.svg

provide detailed alt text to intro image 01.

---

_episodes/01-intro.md

Additional variables as Sticky Notes now has a detailed content: ../fig/python-sticky-note-variables-03.svg

provide detailed alt text to intro image 03.

---

_episodes/02-numpy.md

Operations across axes now has a detailed content: ../fig/python-operations-across-axes.png

provide detailed alt text to numpy image 02.

---

_episodes/01-intro.md

Variables as Sticky Notes now has a detailed content: ../fig/python-sticky-note-variables-02.svg
Related to #781
Followed the recommendations at: https://webaim.org/techniques/alttext/#basics trying to be as specific as possible for the content and the function.

provide detailed alt text to intro image 02.

---

_episodes/08-func.md

Python function structure image now has a detailed description: ../fig/python-function.svg

provide detailed alt text to func image 01.

---

_episodes/02-numpy.md
reference.md

I would suggest to link the term notebook in the second episode to an entry in the reference section which I added in this Pull request. The term has not been introduced before and some students might not know what it refers to.

Add notebook to references

---

_episodes/02-numpy.md

To slice the last three characters, one should use element[-3 : ], which might be a more universal way for any string with length >=3. 
Using element[3:6] refers to the 4th to the 6th characters by its literal meaning.
Please delete this line and the text below before submitting your contribution.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson …

update explanation of the slicing element string

---

_episodes/05-lists.md

I have come across missing information in this line
`Use the step size argument to create a new string that contains only every other character in the string “In an octopus’s garden in the shade”`
In the new correction I have added an the explanation to guide the learner in on what to do to get the desired output.
**New sentence**
Use the step size argument to create a new string that contains only every other `second` character in the string “In an octopus’s garden in the shade”

Added missing explanation bit.

---

_episodes/07-cond.md

`print(abs(a - b) < 0.1 * abs(b))` (and preceding Solution 2) leaves out the edge case where `a` is exactly 10% of `b`. This issue comes down to the interpretation of "within" 10%. Does a number within 10% of another number include the 10% value? 
Assume `b = 100` and `0.1 * b = 10`, then the value 10 is within 10% by definition since 10 is 10% of 100. Now set `a = 100 + 10 = 110` which is `b` plus 10% of `b`. Then `a - b = b + 0.1 * b - b = 0.1 * b`, which is within 10% of b.
The correct test is `abs(a - b) <= 0.1 * abs(b)` to account for this edge case.
<details>
checkout@carpentries.org so we can record your …

Close Enough correction for 07-cond.md

---

_episodes/08-func.md
_episodes/10-defensive.md
_episodes/12-cmdline.md

Replaced single triple quotes by double triple quotes for Python docstrings in episodes 8, 10, and 12.

resolve #848 - use double triple quotes for docstrings

---

_episodes/03-matplotlib.md

As requested in #833, this addition shows an example of how to save a
Matplotlib plot as a graphics file.
<details>
I intended to keep it as short and simple as possible.
I have added a line storing the plot to file *before* the last line `show()`. If the user is not plotting in interactive mode, then the user will have to close the shown plot before the script continues and in that case, there is no plot to store afterwards. Therefore, it is safer to store the plot before we show it.
</details>

Added storing plot to a file to Matplotlib example

---

_episodes/02-numpy.md

Noticed one instance where we don't follow recommended guidelines for keyboard keys (https://carpentries.github.io/lesson-example/06-style-guide/index.html#keyboard-key)

02-numpy.md: wrap 'tab' in <kbd> HTML tag

---

_episodes/09-errors.md

to improve consistency in style. Issue #854

Update episode 9 double-quotes to single-quotes

---

_episodes/05-lists.md

to improve consistency in style. There are two instances '"-1"' and "octopus's garden" left to preserve the quote-in-quote.

Update episode 5 double-quotes to single-quotes

---

CONTRIBUTING.md

The current link returns a 404

Update link target to discuss mailing list

---

_episodes/01-intro.md
_episodes/02-numpy.md
_episodes/03-matplotlib.md
_episodes/04-loop.md
_episodes/05-lists.md
_episodes/07-cond.md
_episodes/08-func.md
_episodes/09-errors.md
_episodes/10-defensive.md
_episodes/11-debugging.md
_episodes/12-cmdline.md
_extras/about.md
_extras/additional_material.md
_extras/discuss.md
_extras/extra_exercises.md
_extras/guide.md
index.md
reference.md
setup.md

See discussion here for more background: https://github.com/datacarpentry/datacarpentry.github.io/issues/542
In short, some Carpentries lessons use `/guide/` for their Instructor Notes page and others use `/guide/index.html` (the default defined in `_config.yml`). This PR removes permalinks with a trailing slash from the YAML front matter of the Instructor Notes (`_extras/guide.md`) and other Extras files, consistent with new lessons created with [the lesson template](https://github.com/carpentries/styles/). Although there's no functional difference in the online versions of the lesson pages, pages with a trailing slash in the permalink will result in **broken links in the version of the lesson built locally**. We'd like local builds to be usable e.g. in workshops taking place at …

make lesson suitable for teaching with locally-built (serverless) pages

---

_episodes/09-errors.md

<details>
In the text, describing the error that occurs (for the very first section of code in the Episode) reference is made to lines 8 and 6. This should be line 11 and line 9.
**The actual original text: (error shown in bold)**
1. The first shows code from the cell above, with an arrow pointing to Line **8** (which is ```favorite_ice_cream()```).
1. The second shows some code in the function favorite_ice_cream, with an arrow pointing to Line **6** (which is ```print(ice_creams[3])```).
**It should read: (correction shown in bold)**
1. The first shows code from the cell above, with an arrow pointing to Line **11** (which is ```favorite_ice_cream()```).
1. The second shows some code in the function favorite_ice_cream, with an arrow pointing to Line **9** (which is …

Fix errors in text to code line references.

---

_episodes/03-matplotlib.md
reference.md

<details>
Added description for heat map to reference.md and linked in 03-matplotlib.md.
As discussed in #888
</details>

Add a description for heat map.

---

.travis.yml

This is to align the rvm ruby version with the github-pages requirement and fix the following that is showing up in the [Travis CI build](https://travis-ci.org/github/swcarpentry/python-novice-inflammation/builds/744477676):
```
$ make site
bundle config --local set path .vendor/bundle && bundle install && bundle update && bundle exec jekyll build
Your Ruby version is 2.5.3, but your Gemfile specified >= 2.7.1
Makefile:49: recipe for target 'site' failed
make: *** [site] Error 18
The command "make site" exited with 2.
```
I had tried to update the .travis.yml file according to what was in [bin/boilerplate/.travis.yml](https://github.com/swcarpentry/python-novice-inflammation/blob/d96200187de2d21ea13fcd22fde336b6f7da4dc1/bin/boilerplate/.travis.yml) after the recent carpentries/styles …

.travis.yml: Specify ruby 2.7.1

---

fig/python-zero-index.svg

When going through the ["Analyzing Patient Data" lesson](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html), I noticed that the figure illustrating zero indexing was cut-off:
This PR widens the viewbox in the SVG slightly to prevent this.

Slightly widened figure to fix cut-off text.

---

_episodes/01-intro.md

Regarding issue #498, shortened the lines in episode-01. 
I checked locally, whether the changes broke anything, but I somehow cannot update ruby right now. So I reduced the requirement in the Gemfile, however, not sure what problems come with this little hack.

[ENH] fix long lines _episodes/01-intro.md 

---

fig/lesson-overview.svg
index.md

<details>
As discussed with @maxim-belkin, added overview figure and clarified the text a bit to add more context to the lesson. 
</details>

Adding figure with lesson goal/overview

---

_episodes/02-numpy.md
_episodes/03-matplotlib.md

As discussed in #830 (and perhaps controversially!) this adds a note to episode 3 to mention that `import matplotlib.pyplot as plt` is a common convention. Note that:
- The same is done in the previous episode for `import numpy as np`. I've used the same heading as that for the pyplot import and kept the content short as it has been seen previously.
- I've put it at the end of the episode, just before the exercises, to try to help avoid cluttering/confusing the flow of the rest of the episode.
Very happy to make any necessary changes based on comments, but I do believe this is a worthwhile addition due to how ubiquitous this syntax is (including in the matplotlib documentation itself).

Add a note on the convention of importing matplotlib.pyplot as plt

---

_episodes/09-errors.md

Fixes long lines in episode 9, converting them to max 100 characters.
Partially addresses #498

Fix long line in episode 9

---

_extras/discuss.md

Alt-text for some images suggested by @maneesha during Core Team Accessibility session. Ready for review.

adding alt-text for some images and illustrations

---

_episodes/03-matplotlib.md

Regarding #498, I fixed lines in _episodes/03-matplotlib.md and CONTRIBUTING.md.
The `make lesson-check-all` command now outputs:
```
./README.md: Line(s) too long: 2, 4, 5, 7, 8, 9, 10, 13
```
However, as noted in #911, it may be a challenge to remove those.

Fix long lines in _episodes/03-matplotlib.md

---

_episodes/08-func.md
_extras/extra_exercises.md
reference.md

This pull request proposes to close #883 by adding a brief note about the switch idiom `a, b = b, a` in  **The Old Switcheroo** exercise and linking to the description of the switch idiom already present in the **Extra Exercises** page.
In the **Extra Exercises** page it also replaces `a, b = [b, a]` with the more idiomatic and simpler `a, b = b, a`.

Add mention of swap idiom to 'The Old Switcheroo' exercise

---

_episodes/01-intro.md

As discussed in swcarpentry/python-novice-inflammation#847, the example in the "Variables as Sticky Notes" callout of Episode 1 makes it sound like the reason that variables don't "remember" where their values come from is a consequence of the fact that variables behave like sticky notes. However, this is inaccurate and could mislead learners. For the moment, some modification of the explanatory text suggested by @ldko has been inserted as a stop-gap until a better example can be crafted.
Closes #847

Improve the explanatory text in the "Variables as Sticky Notes" callout of Episode 1

---

_episodes/01-intro.md

As part of my checkout, I created a short exercise that could be added to the Python Fundamentals episode.
-Zack Chilton

01-intro.md: New fundamentals exercise

---

_episodes/06-files.md

As discussed in #937, introducing `glob` by saying it has an unpleasant name is not optimal. Here we change the introductory statement in a way to rather highlight its functionality.

Change wording about glob being an unpleasant name

---

_episodes/08-func.md
reference.md

<details>
<summary><strong>Reading a global variable inside a function</strong></summary>
As discussed in #934, this is a proposal to say a few words abour reading a global variable inside a function, because this is used later on in a challenge of this episode, and finally listed in the key points.
</details>

Episode 8, functions : about reading a global variable inside a function

---

_episodes/02-numpy.md
_episodes/03-matplotlib.md
_episodes/04-lists.md
_episodes/05-loop.md
_episodes/06-files.md
_extras/guide.md
fig/inflammation-03-imshow.svg
index.md

As mentioned in #909 (and related to #887 and #179), this PR aims to introduce a narrative around the synthetic inflammation datasets used throughout the Lesson. 
Doing so will hopefully help frame the lesson with a more realistic scenario to show how programming can help speed up data science/research/etc, as well as clarifying a few sections in the lesson that make reference to trends in the inflammation data, which otherwise have no context.
The narrative was created for a "condensed" data-driven tutorial that I gave a few weeks ago, and as such it could benefit from additional input rather than just my own thoughts. I'm more than happy to chop/change/remove/add things as desired, but hopefully this provides a meaningful contribution to the lesson and helps give context to the data.

Adding narrative to the datasets

---

_episodes/05-loop.md

Addresses #968 
- fix `for loop` and `list` URLs

fix: modify broken URLs in episode 5

---

_episodes/03-matplotlib.md

This makes the individual episodes a little more self-containted and makes it easier for instructors who may swap out between episdoes.  
It also will mean that we do not need to dis-allow this episode for teaching demos [see PR](https://github.com/carpentries/instructor-training/pull/1346/commits/5ecd1baf934afa0a386c74ee82e29027f7ed8d0c)

re-import data at start of plotting

---

_episodes/02-numpy.md

Fix the URL for `floating-point number`

02-numpy.md: fix broken URL

---

_episodes/01-intro.md

Fixes #966 
Changes gendered term layman to non-gendered layperson. 
I think @matthewabrown's suggestion in #966 to instead avoid the use of lay[man/person] altogether (which I guess could be considered demotivational language in the sense implying the description should be easy to understood which might not be the case for everyone) by replacing the sentence with
> In essence, a variable is a named location for storing, modifying, and recalling a value
or some variant of this has merit, but as this would be a more significant change I've just made a minimal change to swap layman to layperson for now as this seems unlikely to be controversial.

Removing use of gendered term layman

---

_episodes/11-debugging.md

This was using the old percent formatting instead of the more modern `.format` (Python 2.6+) or f-strings (Python 3.6+). What's more, string formatting is not introduced or discussed anywhere else in the lesson, and it is not elaborated here. I think the simplest thing for this is to simply not introduce it here, it's not needed, and multi-argument print calls have been introduced.

fix: use normal print instead of percent formatting

---

_episodes/02-numpy.md

The documentation link was outdated and 404, now redirects to the existing page.

Updated Numpy doc link.

---

_episodes/10-defensive.md

This removes the ```float()``` around a (potential) integer division. Since Python3 the result of an integer division is a floating point number. This also removes the time and attention capacity necessary by learners for an explaination of what this does and why it is there. I do not mean to say that type conversions cannot be important, but the focus of this excercise is elsewhere.
Note: it was good to have this in place for Python2, but Python2 is dead today and has been for a while. We also require an installation of Python3 in the setup.
<details>
checkout@carpentries.org so we can record your progress. You've …

remove unnecessary type conversion

---

index.md

This specifies a minimum supported Python version. There was a discussion on discuss.python.org about stating "Python 3" vs. a minimum, and the consensus was that you should always state a minimum, rather than a generic "Python 3". Nothing actually works on Python 3.0 (such as NumPy), so it doesn't make sense to treat this as "Python 3", but rather as "Python 3.x". Currently it shoud work just fine on 3.5+, but I think it's best to avoid recommending EoL Python versions.
This will also enable the debugging lesson to use `breakpoint()`, and turn into a real lesson on debugging eventually, if desired. F-strings are something else that might be worth teaching.

chore: specify the minimum supported version

---

_episodes/09-errors.md
_episodes/10-defensive.md

This was a holdover from Python 2. While cleaning it up, added recommendations for using newer Pythons for better error messages. The biggest leap is likely the upcoming 3.11, though 3.10 gives big improvements for several situation including invalid syntax.

chore: touch up error handling for modern Python

---

_episodes/02-numpy.md

This section of the lesson is inconsistent. It uses data[30,20] as a midpoint but states that this is the 30th row and 20th column.
Either the indices should be changed (per PR) and the text updated a little or the text should be changed to reflect that this is the 31st row and 21st column (not 30th and 20th).
<details>
respond to your contribution. Although not all …

Base "middle" on 0-index consistently

---

_episodes/10-defensive.md

In lesson `10-defensive.md` under the section `Test-Driven Development` assertions statements are executed without the function `range_overlap` being available in the namespace. 
This actually will yield a `NameError`:
```python
assert range_overlap([ (0.0, 1.0) ]) == (0.0, 1.0)
>>> NameError: name 'range_overlap' is not defined
```
However in the episode, it is stated that this will raise an `AssertionError` which is not correct:
Instead of changing the error I opted to define `range_overlap` first without body, as I learned it as standard procedure for tdd:
```python
def range_overlap(ranges):
pass
assert range_overlap([ (0.0, 1.0) ]) == (0.0, 1.0)
>>> AssertionError:
```
That way the tests can be triggered and raise the expected `AssertionError`, without changing the general flow of …

CHG: Bring empty function into namespace for tdd

---

_episodes/02-numpy.md

The alternative solution of using numpy.delete() to remove a column from an array is helpful, but the meaning of the arguments is not obvious without explicitly including the names. Even then, "obj" is non-obvious, so I also added a note in the solution description reminding them to use help files if necessary.
<details>
respond to your contribution. Although not all …

Add explicit parameters for numpy.delete

---

setup.md

I'm updating these links because the commonmark parser does not recognise them and my intervention did not account for this situation. This is the only place in this or any of the other lessons I have modified where this happens, so it's easier for me to update this than to update my intervention and add tests.
FWIW, the link syntax in The Workbench is _much_ simpler:
https://carpentries.github.io/workbench/transition-guide.html#internal-links

[workbench transition] Update setup.md

---

episodes/08-func.md

This fixes #1013 by updating the example output and removing mention of the difference being "very small" - it is now calculated as 0.0.
The second commit also removes the middle of this sentence:
> The mean of the offset data isn’t quite zero — we’ll explore why not in the challenges — but it’s pretty close.
because, as far as I can tell, we do not actually "explore why not in the challenges"

Update example output

---

CONTRIBUTING.md

The Contributing Guide, CONTRIBUTING.md, contains two links with URLs that should be updated:
* the How to Contribute to an Open Source Project on GitHub link which used to lead to a 404 has now been updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
* the [repo] link reference which used to point to a placeholder URL (https://example.com/FIXME) has been updated with the current repository url.

[UPDATE] urls to resources in Contributing Guide

---

episodes/12-cmdline.md

Add a reference to the argh library to make it easier for people to get started with command line interfaces in Python.

Added argh reference

---

episodes/04-lists.md

The key points were broken in episode 4 due to math rendering. This is a quick fix.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.
---

FIX: Correcting line breaks for episode 4 on lists

---

episodes/05-loop.md

Adjusted the wording of the exercise using `range` in episode 5, to fix the confusion raised in #1053 
I chose to keep the "Using `range`", since the other wording might imply that `range` should do the printing. (I recently encountered a learner trying to call `range` directly for this challenge rather than using a loop with `print` in the body.)

adjust wording of range exercise; fix #1053

---

learners/setup.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
This switches floating solution divs in the setup instructions for the `spoiler` class introduced in the recent release of the lesson infrastructure
_If any relevant discussions have taken place elsewhere, please provide links to these._
See https://github.com/carpentries/sandpaper/pull/502#issuecomment-1698203526 for an example of a spoiler class div in action.

use spoiler divs for expandable launch instructions

---

episodes/07-cond.md

We ran into the problem described in the proposed instructor note when we taught based on the course material recently.
It should be in front of the first example that potentially causes the error.

Inform instructors about potential syntax error

---

episodes/10-defensive.md

The description of the exercise used the term list, while the code in the solution used functions that we have so far only used with NumPy arrays (`amax`, `amin`). Even though these functions do take arguments of type `list`, learners might get confused (and teachers do get confused, because I thought up until I tested it right now, that surely `numpy.amin` etc. do not work on `list` type objects… :)).

Do not refer to NumPy array using the term list

---

index.md

This is in relation to Issue #1070 
```
The section on prerequisites notes that you should be using any current Python version 3.7+.
Python 3.7 hit EOL on 2023-06-27. This callout should be updated to refer to 3.8+
```

Update Py version to 3.8+ as 3.7 has reached EOL - issue #1070

---

learners/reference.md

The `reference.md` file that contains the glossary has "FIXME" as a title, and has the "Glossary" heading twice.  This PR fixes both of those issues.

Fix "FIXME" in Glossary page title

---

learners/reference.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
N/A
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
In the [carpentries glosario repo](https://github.com/carpentries/glosario/issues/384) it was raised that it could be helpful for some learners to include the definition of "debug".
This PR adds the "debug" term to the glossary, using a shorter variant of the definition given in [glosario](https://glosario.carpentries.org/en/#debug)
_If any relevant discussions have taken place elsewhere, please provide links to these._
The suggestion comes from [issue #384 in the glosario repo](https://github.com/carpentries/glosario/issues/384)
<details>
For more …

Add debug term to glossary

---

learners/reference.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Fixes #1098
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Adds a definition for "whitespace" to the lesson glossary. The definition is taken from [Glosario](https://glosario.carpentries.org/en/#whitespace).
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some …

Add definition for whitespace

---

episodes/01-intro.md
episodes/08-func.md
episodes/11-debugging.md

This adds a new section to the first episode about how to get help with writing & debugging Python, including a discussion of generative AI in this context. It is based on the changes made and discussed in swcarpentry/python-novice-gapminder#697 (and in various other communication channels -- please see the linked PR thread for more details)
This moves the first mention of the built-in `help` function earlier in the lesson (it was previously in episode 8), and briefly discusses some things that are then covered in more depth in the _Debugging_ episode.
This might feel redundant but IMO it is sensible to discuss strategies for getting help early in the lesson. Furthermore, the guidance added here about how (not) to use LLM assistants while learning to code needs to appear early on.
This …

Add a section to the intro on getting help
