02-func.html, 02-func.md
I will merge this without waiting for review since this change is **very small** and **important**.
=> Add missing begin of code block

discussion.md, motivation.md
This fixes #14 (though the files need to be filled in).
=> Adding missing files

06-cmdline.md
This was demo in instructor training - more changes to come
=> Run whole command line lesson from command line

01-numpy.md
Changed variables in examples to illustrate why age and weight might suddenly change.  Semantically the same as before, but at least a *little* more compelling.    If the astronaut travels at FTL, someone might try to work out what would happen to the age in that case :)
=> Make the challenge slightly more domain specific

03-cond.md
A common misconception with conditionals is learners expecting all true blocks to be executed when in reality only the first true block is executed. This multiple choice question provides a quick check to see if the student has picked this up with multiple elif statements.
This is mentioned in the notes for if/else blocks, but not specifically for elif so is worth reiterating in a challenge.
=> Add challenge question for multiple true branches

02-loop.md
I have suggested a challenge entitled "What does this code do?" that aims to pull together ideas of loops and indexing and letting the student make the link to multiple layers of indexing, e.g. [string in list][character in string]. 
This challenge (along with other challenges in this lesson) may be better suited to being inlined with the lesson. If this challenge were to be set directly after the section on lists, it would allow students a pause to review their new knowledge and take some of the ideas further than they have currently been taught (logical extension of the presented material).
=> Added an indexing and loop challenge

05-defensive.md
The phrasing was slightly confusing, as the second part might have referred to the program, rather than the assertions.
=> Adjusted phrase to clarify the learning objective

instructors.md
This imports instructor's material from the old `bc` repository.
=> Starting to write instructor's guide

01-numpy.md, 02-loop.md, 04-func.md
Existing example plots use MATLAB style. Updated to use a more Python like style (i.e store the plots and axes in variables) but keeping as close as possible to exisiting code so the challengws etc should be unaffected.
=> Change plotting examples to use Python rather than MATLAB style

02-loop.html, 02-loop.md
In response to #48 removed functions from loop lesson. I'd appreciate an independent review to make sure this seems reasonable without the functions.
=> Remove func from loop

06-func.html, 06-func.md, 07-defensive.html, 07-defensive.md
It's not entirely obvious what `running` does in the challenge on 'Testing Assertions'. Added some documentation to make it a little bit more clear.
=> Add documentation to aid understanding in challenge

05-cond.html, 05-cond.md
=> Changed =< to ==

index.md
Spotted this while preparing for workshop 2015-05-12-BUSM!
=> Fix typo in index file

05-cond.md
=> Issue #72 initialize variables in tuple challenge

instructors.md, tools/gen_inflammation.py
Also included the gen_inflammation.py script that was in the old `bc` repository. This seems a good place to put it, since it is Python after all...
Fixes #46.
=> Write a legend for the instructor guide

09-debugging.md
N^(2/2) = N, I think you mean N^2, especially because N^2 is referenced  two paragraphs below.
=> Fixing typo in N squared

05-cond.md
The concept of using an if statement to check the inflammation data is introduced at the end of this lesson but is never actually executed to check that it works. I've added some content that does just that.
I think this is a particularly nice segue into the following lesson on functions. The way I've written the end of the lesson requires repetition / cut and paste, which is something that can be avoided by using functions...
=> Added execution of final if statement to 05-cond.md

06-func.md
This pull request fixes a typo in the markdown for one of the output cells and also updates the challenges in `06-func.md` so that they are more consistent with the order in which particular concepts are introduced throughout the lesson.
=> Update to challenges in 06-func.md 

06-func.md
The `analyze` function is now defined by the instructor during `06-func.md`, so I've deleted the challenge that asks the learner to do exactly the same thing.
=> Deleted analyze challenge

05-cond.md
Current versions has answers on one line like this: "A B C B and C". This commit changes it to
1. A
2. B
3. C
4. B and C
=> Small fix to make answers to challenge appear correctly

03-lists.md
As issue https://github.com/swcarpentry/python-novice-inflammation/issues/84 pointed out, there were no exercises for the lists module, so I wrote this one. It hasn't been tested in a software carpentry setting (that I know of), but it worked well in the Intro to Python class that I TAed. It hints at the idea of accumulators, which I think is valuable to touch on.
It would probably be good to also have an exercise or two that deals with indexing into lists, but I'm having trouble coming up with one that is neither obvious from the examples nor really convoluted.
=> Added exercise on lists

01-numpy.md
Small commit to finish instructor training for Blake Joyce (University of Arizona). Fixed commit errors with spacing.
=> Added single line about libraries for instructor training

instructors.md
This replaces PR #99. I think all of the changes requested by @abostroem have been made. Since the discussion about where to put the solutions is still ongoing (see [lesson-template#267](https://github.com/swcarpentry/lesson-template/issues/267)) I haven't done anything about that.
I hope to get to the solutions for 10-cmdline at some point.
=> Instructor solutions update

01-numpy.html, 02-loop.html, 02-loop.md, 03-lists.html, 04-files.html, 04-files.md, 05-cond.html, 06-func.html, 06-func.md, 07-errors.html, 08-defensive.html, 09-debugging.html, 10-cmdline.html, discussion.html, index.html, instructors.html
This pull request incorporates changes to source files needed for using Python 3 in our lessons, and regenerates the HTML.
=> Finishing conversion to Python 3

01-numpy.md
Reverts swcarpentry/python-novice-inflammation#158
Questioning whether this is really grammatically more correct. Can someone with a better grasp of english grammar confirm?
=> Revert "Minor grammatical change."

02-loop.html, 02-loop.md
These are my small fixes to a lesson as part of instructor training. It's a couple of small stylistic/grammatical things, nothing too major. I initially missed the instruction to only edit the Markdown files and instead made edits to the HTML, hence the multiple commits.
=> Cleaned up some sentences

02-loop.md, 03-lists.md, 04-files.md, 05-cond.md, 06-func.md, instructors.md
The last time I taught a noted a number of annoying small typos scattered throughout the lessons. Fixing these here.
=> Many little fixes

instructors.md
See currently-rendered website of the lesson in this section.
=> White space is needed here for proper rendering.

01-numpy.md, 02-loop.md, 03-lists.md, 06-func.md, 07-errors.md, 10-cmdline.md, discussion.md, instructors.md
In going through the Python 3 runthrough (see #153) I saw a bunch of little things that I felt should be changed.
Note that this branch is based off of #153 (i.e., it picks up where that PR leaves off -- it assumes that that PR has already been merged) so I recommend that we deal with #153 first, and even merge `py3k` into `gh-pages` before looking at this PR (it'll make merging much simpler).
I also think that we should ensure that these fixes aren't already done in other PRs. I was just blindly going through and changing things I saw that needed changing, but some of them struck me as things I've seen fly through my email at one time or another, and I definitely would rather an earlier PR be merged before looking at this one.
The history of this PR will be easier to read once those …
=> Many small changes from runthrough

05-cond.md
Fixes a tiny inconsistency between input and output messages.
=> Make output consistent with input in lesson 5.

index.md
=> Adding instructions to starting ipython.

01-numpy.md, 02-loop.md, 03-lists.md, 04-files.md, 05-cond.md, 06-func.md, 07-errors.md, 09-debugging.md, Makefile, tools/gen_inflammation.py
After reviewing the lesson for instructor training, I've put together several small changes that fix minor issues like typos, etc..
=> Small changes from review

07-errors.md, reference.md
Dictionaries haven't been introduced at that point and aren't used
outside this lesson. So they have been replaced by a container that
has been introduced and is used heavily: strings.
=> removed notion of dictionaries

01-numpy.md
Having the link to the NumPy documentation might be useful for people exploring its capabilities.
=> Added link to NumPy Documentation

05-cond.md
Adding exercise for instructor training. It checks that the learner can apply if/elif/else correctly and requires also the application of for loops and lists which were covered in previous lessons.
=> Add if/elif/else exercise. (instructor training)

05-cond.md
This exercise combines concepts from the lessons on loops and conditionals.
This submission is required as part of my instructor training.
=> Add an exercise (counting vowels) to lesson 5.

05-cond.md
This is for the Software Carpentry's Instructor Training.
=> added challenge to 05-cond.md

06-func.md
I add an example of function with a parameter to lesson "Programming with Python" topic Creating Functions.
=> example of function with parameters

04-files.md
Contributed a new exercise to section 4.
=> new exercise for part 4

09-debugging.md, instructors.md
This exercise has the aim of ensuring learners are able to step through
unseen code with unexpected output to locate issues.  The issues present
are that the loop is not being utilised correctly (height/weight always
set as the first patient's data) and that the height/weight variables
are reversed.
=> Add debugging challenge (part 09)

02-loop.md, 04-files.md
I made two changes. On the lesson "Repeating Actions with Loops", I expanded the example a bit on looping through a string. And on the lesson "Analyzing Data from Multiple Files", the glob example was trying to "glob" the files that were not in student's working directory for the lesson. I changed it so that the "glob" will list of files in the student's working directory.
=> Improving Python lessons a bit 

06-func.md
The exercise looks at what happens when immutable objects are passed into a function. People without previous programming experience might assume that it's possible to swap 2 numbers using a function written like this. And people with limited programming experience in C or Java (or C-like languages) might see the example code and wonder if, when it comes to primitive types, Python is pass-by-value or pass-by-reference. The answer is that Python is neither. This exercise provides the opportunity to have a discussion about this particular part of the language.
There's a fairly good discussion of how arguments are passed into functions in Python here: https://jeffknupp.com/blog/2012/11/13/is-python-callbyvalue-or-callbyreference-neither/ and the Python docs on how to deal with the problem …
=> Suggesting new exercise for the Creating Functions page

03-lists.md
Includes a short description of slicing in steps, and an exercise to test the learner's understanding of this. The section assumes that the basics of slicing have already been introduced.
=> Slicing steps exercise

03-lists.md
Includes sections covering slicing of sequences, with examples and an exercise to test a grasp on simple slicing. The second section then covers slicing from the beginning or to the end of a sequence by omitting the first or second range index respectively.
=> Omitting slice indices

06-func.md
I created a new exercise to introduce the concept of self-documenting code and give learners a chance to reflect on their coding style and practice reviewing code with a partner.
=> New self-documenting code exercise

07-errors.html, 07-errors.md
This is my ever first pull request, so if I did not do everything right or did not say the right things, it was not intentional. Thanks
=> Corrected a typo on the lesson.

setup.md
=> Fixing link to ZIP file

index.md
Adding a 'Getting Started' section with a reference and link to the 'Setup' tab, so people know where to look for installation instructions and the data.
=> added Getting Started directions to index.md

_episodes/01-numpy.md
This addresses one of the comments from #287, which was about a sentence relating to counting indices from zero being unclear. I can work on it further if needed, but I think it should already be a little clearer now.
=> Clarify sentence related to counting from zero

_episodes/05-cond.md
Challenge is not currently appearing on https://swcarpentry.github.io/python-novice-inflammation/05-cond/
=> fix quotation, indentation

_episodes/01-numpy.md
This is my first PR for a Software Carpentry lesson, so please don't hesitate to correct my procedure.
The way I interpreted the challenge, it is necessary for the trainee to avoid removal of singleton dimensions that can result from indexing. I don't think the solution gets ahead of future lessons, but perhaps an maintainer could say?
=> Adds solution to challenge `Stacking Arrays` in episode one

_episodes/06-func.md
This adds a solution for the Mixing Default and Non-Default Parameters exercise in the Creating Functions lesson.
=> Add solution to Mixing Default and Non-Default Parameters exercise

_episodes/02-loop.md
This is a maths-based example for `enumerate` in reference to issue #276. I found it a bit difficult to find a use for `enumerate` which wasn't better served with `zip` or slicing. An obvious one is to report errors on line / column numbers, but that usually requires `if`, which hasn't been introduced yet.
[This is my instructor training checkout contribution]
=> Added exercise for enumerate in loops lesson

_episodes/08-defensive.md
=> Fix issue #329

01-numpy.md, 02-loop.md
Additional callout for arbitrary loop variable names, and importing numpy as is, and as np.
=> 2 small changes

_episodes/01-numpy.md
This commit adds an exercise to the first episode dealing with handling
tabular data longitudinally by taking the differences between
inframmation readings.
=> [Instructor Training Checkout] Add an longitudinal tabular data exercise.

_episodes/02-loop.md
The formatting in this callout doesn't render for me. I've updated it to what I think it should be.
=> Formatting in 02-loop.md in the "What's in a name?" callout is messed up

Makefile
Tweaking make help message to clarify when it is appropriate / necessary to rebuild figure page.
=> Tweaking make help message

_episodes/01-numpy.md, _episodes/02-loop.md, _episodes/03-lists.md, _episodes/08-defensive.md, _episodes/09-debugging.md
The following fixes result from running this tutorial during a [Software Carpentry Workshop at the Earlham Institute](http://earlham.ac.uk/software-carpentry-workshop-2017) together with @froggleston and @tonietuk.
See individual commits for details.
=> Post-workshop fixes

_episodes/03-lists.md
Demonstrate two variables assigned to the same list where changing one
changes both. Demonstrate making a copy of a list with a new variable
name.
=> Add code examples to ch-ch-ch-changes

_episodes/01-numpy.md
Added R to list of programming languages using 1-based indexing.
It seems logical to point out this difference for R in particular because it's such a commonly used and taught language.
=> Added R as another example of a 1-based indexing

_episodes/04-files.md
Added solution to Generate Composite Statistics (instructor check out procedure)
=> Generate Composite Statistics - solution

_episodes/06-func.md
The __solution__ was named __challenge__ by mistake.
=> change challenge to solution

_episodes/08-defensive.md
Post-condition now takes account of average of a list with single value. Changed "input" to "input_list".
Fix #330 
c/c @bmcfee
=> Better solution for pre- and post-conditions

_episodes/01-numpy.md
It's good to emphasise the use of variable names that are more descriptive. One letter variables may provide room for errors in longer scripts.
Please delete the text below before submitting your contribution.
=> change variable 'x' to 'x_val'

setup.md
Small modification to point to the correct part of the setup page i.e. where the instruction to configure python and use anaconda are
(resolve #401).
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any …
=> Update linked to install anaconda.

code/arith.py, code/check.py, code/line_count.py
Fix for [issue #410](https://github.com/swcarpentry/python-novice-inflammation/issues/410).
Backwards compatible with python2 as well.
=> make print statements python3 compatible

CONTRIBUTING.md, _episodes/03-lists.md
---
This contribution is for instructor training.
---
After reading through the episode 03 about python lists, I feel that the episode teaches much knowledge about using lists. Some topics covered by the episodes are not reflected by the current learning objectives. Therefore, several measurable learning objectives are added to the episode.
=> Add More Learning objectives for Episode 03 on Learning Python Lists

_episodes/02-loop.md
Updated text describing enumeration with a clearer description.
=> Update 02-loop.md with enumeration description

_episodes/02-loop.md
Agreed.
Making suggested change to lesson 2
=> Issue #419 - making suggested change to lesson 2

_episodes/04-files.md, _episodes/05-cond.md
Fixing some of https://github.com/swcarpentry/python-novice-inflammation/issues/431
Did my instructor training recently, this is me doing my bit by way of contributions.
I will take a look at the last bit of issue 341 too - the Command-Line Programs episode bit.
=> Fix some of issue 431

_episodes/05-cond.md
Added a `numpy` import to address issue #442
=> Add missing numpy import

_episodes/01-numpy.md
=> Make row,column indexing convention clear early on

_episodes/03-lists.md
We taught this lesson today. Someone commented on the "diverse professions" of the scientists... but it'd be nice to have diverse role models in our examples. Small but well-meaning change.
=> Swap Newton with Curie

_episodes/01-numpy.md, _episodes/02-loop.md, _episodes/03-lists.md, _episodes/04-files.md, _episodes/05-cond.md, _episodes/06-func.md, _episodes/07-errors.md, _episodes/08-defensive.md, _episodes/09-debugging.md, _episodes/10-cmdline.md
I updated the python novice inflammation lessons to add syntax highlighting when displaying python or bash source code. I followed recommendations given at http://swcarpentry.github.io/lesson-example/04-formatting/index.html
=> Added syntax Highlighting for displaying python and bash source

_episodes/04-files.md
=> Correct solution to 'plotting differences'

_episodes/05-cond.md
=> Use startswith in solution to exercise #464

_episodes/01-numpy.md
Changes to the "Change In Inflammation" example:
Added explanation of numpy.diff(), including an example.
Corrected grammatical problem in the second sentence of the first paragraph.
Fixed spelling of "difference" in first Solution.
=> Change In Inflammation: Added explanation of numpy.diff()

_episodes/02-loop.md
Surround em dash characters with whitespace. This better matches the formatting used in later sections in the Programming with Python lesson.
=> Update 02-loop.md — em dash formatting

_episodes/06-func.md
=> Improve clarity and robustness in 'tidying up'

_episodes/04-files.md
Fix #441
Well actually, 441 has already been fixed, but this relates to the same
exercise, and issue 441 hasn't been closed yet.
=> Fix typo in 'composite statistics' exercise

_episodes/03-lists.md
Correct spelling of 'Numpy' to 'NumPy'.
=> Update 03-lists.md – spelling correction

_episodes/03-lists.md
Hello!
For reference: https://www.python.org/dev/peps/pep-0008/#inline-comments
Best,
Marianne
=> Separate inline comments by at least two spaces.

_episodes/06-func.md
I added an exercise making clear the difference between return and print. As asked for in issue:
https://github.com/swcarpentry/python-novice-inflammation/issues/506
Lines are approximately 807-850.
This is part of an check-out exercise (if accepted).
=> Return vs print exercise

_episodes/06-func.md
… GH Issue: Long lines in lessons #498
_episodes/06-func.md
Line(s) are too long: 46, 69, 229, 358, 371, 406, 409, 426, 502, 519, 542, 621, 710, 927, 999
=> 06-func.md: fix long lines

_extras/guide.md, index.md
- Moved text from `index.md` to `Instructor Notes` (`guide.md`)
- Simplified `index.md`
=> Move discussion from index to Instructor Notes

_episodes/01-numpy.md
See discussion here: https://github.com/swcarpentry/python-novice-inflammation/pull/538
=> 01-numpy.md: fix typos, reword, improve

_extras/guide.md
Use proper link to `gen_inflammation.py` script
=> guide.md: fix link to gen_inflammation.py

_episodes/03-lists.md
An example about heterogeneous lists as many users could encounter this issue.
=> Added a callout box about heterogeneous lists data as suggested in #541

_episodes/01-numpy.md
Per the discussion on issue #452, changing the estimated time for Lesson 1.
=> 01-numpy.md: update time estimates

_episodes/05-cond.md
Numpy has been already imported, so there is no need to do it again.
CC @ldko @annefou
=> 05-cond.md: explain the need to import numpy library

_episodes/05-cond.md
… conditional statement
https://github.com/swcarpentry/python-novice-inflammation/issues/444
=> Clarify 'checking our data' example by naming some values

_episodes/05-cond.md
as these are not actually printed
=> Remove quotes from output

_episodes/06-func.md
=> fix long lines _episodes/06-func.md #498

_extras/additional_material.md
=> fix long lines _extras/additional_material.md #498

_episodes/07-errors.md
=> fix long lines _episodes/07-errors.md #498

_extras/discuss.md
=> fix long lines _extras/discuss.md #498

_episodes/05-cond.md
=> fix long lines _episodes/05-cond.md #498

README.md
=> fix long lines README.md #498

_episodes/03-lists.md
=> fix long lines _episodes/03-lists.md #498

reference.md
=> fix long lines reference.md #498

_episodes/02-loop.md
Both examples will work but 4 is more standard and I believe we should
teach participants to get 4 into their muscle memory and not 3 spaces.
=> change indent from 3 spaces to 4

_episodes/06-func.md
"four spaces good, two spaces bad"
Use consistently 4 (which is the standard) instead of
mostly 4 and sometimes 2.
=> more consistent indentation in functions

_episodes/04-files.md
as  suggested in https://github.com/Sabryr/python-novice-inflammation/pull/new/issue_597, I am submitting this PR for review. If you think this is a good suggestion I would appreciate  if this is integrated. 
If you had a reason for the original solution provided, then this PR could be rejected and we can use this as a discussion point. 
https://swcarpentry.github.io/python-novice-inflammation/04-files/index.html
Use numpy in the solution for Plotting Differences
Thank you.
=> Use numpy in the solution for Plotting Differences Fixes #597

_episodes/02-loop.md
Following on from #602, this clears up the term in episode 2. (Using 1 PR per episode as requested.)
=> Clarify lesson-episode term (Episode 2)

_episodes/01-numpy.md
Added solution for "Check Your Understanding" exercise
=> 01-numpy.md: add a solution for an exercise

_episodes/02-loop.md
Addressed issue #535 - Another reason why for loops are useful.
3 changes
1) Added a third reason, called "Maintenance:"
2) Added the explanation for the third reason.
3) Changed the titles of the two reasons to be in line with the change.
=> 02-loop.md: Another reason why for loops are useful

README.md
Addresses some points raised in #495 and broken out from #610.
=> Adds LICENSE section and links to Instructor Notes to README

README.md
Use reference links in the episode table
=> README.md: episode links

README.md
Add a time column to the episode table. The format to be used in this column is up for a discussion. Our options (Teaching time = L, Exercise time = E, Total time = TT)
1. TT
2. L/E
3. L+E
4. L\<br>E
5. L min / E min
Other?
This PR implements option 2 above but skips `/0`.
Please cast your vote with an emoji:
1 - 👍 
2 - 👀 
3 - 😄 
4 - 🎉 
5 - ❤️ 
React with 👎 if you think this column is not necessary.
=> README.md: Episode table: add 'Time' column

fig/README.md
Follow-up to #555 for clarity, concision, fluidity. Open to discussion!
=> Rephrase fig/README.md

_episodes/03-lists.md
The variable name in the demo is `odds` not `odd`. Correcting this small typo.
=> Typo correction

index.md
I want to help clarify the meaning of the numbers in the dataset. For a long time, whenever I read this lesson, I got hung up with not understanding what the numbers mean. Although the sentence prior to the illustrative dataset says it: "data sets of their daily inflammation", I did not get what those numbers mean. I added these two sentences to help clarify.
Wirawan
=> Added a few sentences to help clarify the meaning of the data set.

_episodes/02-loop.md
Use the phrase "generates a sequence" to use consistent language for lazy-evaluators as iterables in a for loop and avoid suggesting that the sequence is stored as an array in memory.
See issue #491.
=> Lesson 02 - Rephrase "range" object return value - See Issue #491

_episodes/02-loop.md
I added a for loop question in there.
=> 02-loop.md: add a new exercise on loops

_episodes/02-loop.md
Fix for swcarpentry/python-novice-inflammation#421
CC @annefou
=> 02-loop.md: fix exercise

_episodes/01-numpy.md
Removed extra space and updated wrapping
Please delete this line and the text below before submitting your contribution.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a …
=> Updated as per asked

_episodes/03-lists.md
In the section Turn a String Into a List
kindly change
species = binomial_name[11:23]
=> Update 03-lists.md : species = binomial_name[11:23]

_episodes/05-cond.md
=> Fix typo in Conditionals section

_episodes/09-debugging.md
I may misunderstand the intent here, but if by "can interact in..." in "N things can interact in N<sup>2</sup> different ways", we mean something like "can be arranged in...", i.e. permutations, then should we say "N!" here instead (e.g. A, B, C => ABC, ACB, BAC, BCA, CAB, CBA, i.e. 3! ways)?
For example, if we have 3 monadic functions f, g, and h that can be freely composed, then we could have 3! ways of composing them without repetition: f(g(h)), f(h(g)), g(f(h)), g(h(f)), h(f(g)), h(g(f)).
=> 09-debugging.md: number of possible interactions between bugs in code

_episodes/01-numpy.md, reference.md
Given the new location of the callout box, I've updated the text to make the lesson flow more logically.
=> Updated the library import callout

_episodes/04-files.md
It all started with a typo fix (leftmost plot*s*)...
=> 04-files.md: reword 'Plotting Differences' callout box

_episodes/08-defensive.md, _extras/extra_exercises.md
Related to: #708 
The last exercise has a few issues:
a. it uses unclear language ("Fix" may refer to many things)
b. it uses functions not (currently) introduced in the lesson -- builtin `max` and `min`
Both issues can be fixed. Until then, we're moving this exercise to "Extras"
=> 08-defensive.md: move the last exercise to 'Extras'

_episodes/09-debugging.md
5 or 10 minutes to complete exercises seems reasonable for this episode. The first exercise could take awhile so perhaps 10 minutes is closer to the mark.
=> Update 09-debugging.md: exercise time

README.md
Adding @ldko to the list of maintainers of the lesson.
Lauren, maintainers are sorted by their last names, so your name appears between Anne's and Valentina's. Please feel free to update this PR as necessary (e.g., change the link name or destination) -- I'm keeping "Allow edits from maintainers" checkbox on -- and merge it.
Welcome 🎉 !
=> README.md: add Lauren Ko as a maintainer.

setup.md
Jupyter Notebook with capital N
Anaconda distribution with small d (not in title)
"plain vanilla" in small also in option
=> Fix capitalization

_episodes/02-loop.md
=> Update loop variable names for ep2

_episodes/04-files.md
=> Update loop variable names for ep4

_episodes/05-cond.md
=> Update loop variable names for ep5

_episodes/06-func.md
=> Update loop variable names for ep6

_episodes/08-defensive.md
=> Update loop variable names for ep8

_episodes/10-cmdline.md
=> Loop var names ep10

code/check.py
=> Update loop variable names in code file

code/readings_01.py
=> Update loop variable names in code files

code/readings_04.py
=> Update loop variable names for code file

code/readings_08.py
=> Update loop variable names

_episodes/02-numpy.md
This removes the portion of the Analyzing Patient Data episode that teaches common arithmetic operations with arrays. Doing this helps to shorten the episode by removing content that is not used as the lesson progresses.
=> 02-numpy.md: Remove array arithmetic

README.md
- added 'About Software Carpentry' and 'About The Carpentries' sections
- added a few missing dots
- added missing links in the "License" section
=> README.md: add notes about SWC and The Carpentries

_episodes/06-files.md
changes not to use in place operators, which are being introduced in a later lesson
=> update exercise "generate composite statistics"

_episodes/02-numpy.md
Update introductory text in "Loading data into Python".
Reasons:
- justify the need to load data
- remove `access a library` as it seems rather vague
- add a comma before `which stands for`
- change `you want to do fancy things with numbers` to `you want to do fancy things with lots of numbers`
=> 01-numpy.md: Loading data: update introductory text

_episodes/07-cond.md
Flowchart conditional image now has a detailed description: ../fig/python-flowchart-conditional.png
=> provide detailed alt text to cond image 01.

_episodes/05-lists.md
#781 
Add alt-text to pepper image in 05-lists
=> Add alt-text to 05-lists

README.md
I honestly didn't realize I was still listed as a Maintainer on here.
=> Removing my name from the Maintainer List

_episodes/02-numpy.md
<details>
<summary><strong>Changes</strong></summary>
Added a period after the quotes and then put a space before the new sentence on line 279
\- Senate Pearl Lekomola
</details>
=> New branch

_episodes/07-cond.md
This will close #840 by introducing learners to `abs` and hinting they should use it in the solution to the "Close Enough" challenge.
=> 07-cond.md: Introduce `abs`, linking to documentation

_episodes/07-cond.md
to improve consistency in style. Issue #854
=> Update episode 7 double-quotes to single-quotes

_episodes/01-intro.md
<details>
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> Rephrasing the Check Your Understanding question in Episode 1

_episodes/09-errors.md
Fixes #858 
Updated the output as shown in jupyter notebook
=> 09-errors: Update the line numbers in the error block 

_episodes/08-func.md
Is missing a `print()` so output was not shown
=> Fix exercise with f2k

_episodes/04-loop.md
Sorry, I forgot I needed to fork the repo.
=> Adding forward link to episode about lists.

setup.md
This should take care of addressing the broken paths for #880
=> Fix image paths for setup

_episodes/07-cond.md
Added quick explanation of comparison operators, didn't want to bloat the message so hopefully it's the right level of detail - happy to change anything if you'd like. 
Closes swcarpentry/python-novice-inflammation#853
=> Add explanation of comparison operators

_episodes/03-matplotlib.md
Related to issue #781
<details>
Extended description for Heatmap image in 03-matplotlib.md
</details>
=> Added an image description for linflammation-01-imshow.svg in 03-matplotlib.md

_episodes/02-numpy.md
Regarding issue #498:
Shortened linebreaks in episode-02. As in #900, had to reduce the Ruby version in the Gemfile to check locally - but it does not seem to break the episode.
=> [ENH] fix long lines _episodes/02-numpy.md 

_episodes/03-matplotlib.md
Regarding issues in #498, fixed long lines in episode 3.
=> 03-matplotlib.md: Fix long lines

_episodes/04-loop.md
Regarding: #498 
Fixed long lines in episode 04.
=> 04-loop.md: Fix long lines

_episodes/05-lists.md
As described in #498, fixed long lines in episode 05.
=> 05-lists.md: Fix long lines

_episodes/07-cond.md
Regarding #498, fixed long lines in episode 07.
=> 07-cond.md: Fix long lines

index.md
This adds a title and alt text for the lesson overview image in index.md. Also, it shortens one line in the file that was over 100 characters in length. ping @maxim-belkin does this alt text work for you?
=> index.md: add lesson-overview alt text

_episodes/06-files.md
=> Provided detailed alt text for episode 6 inflammation-01.csv

_episodes/04-loop.md
Added an image description for loops_image.png in 04-loops.md (issue #781)
=> Added an image description for loops_image.png

_episodes/11-debugging.md
Fixes long line in episode 11,  making it 100 characters max.
Partially addresses #498
=> Fix long line in episode 11

README.md
Fixes long lines in README.md.
Partially addresses #498.
=> Fix long lines in README.md

setup.md
Fixes long lines in setup.md, converting all of them to below 100 characters.
Partially addresses #498
=> Fix long lines in setup.md

_episodes/02-numpy.md, reference.md
=> Add 'Tab completion' to the Glossary

_episodes/03-matplotlib.md
- Improve image description for 5 figures in _episodes/03-matplotlib.md as suggested by @ivastar in #781
=> Episode 3: improving image descriptions

_episodes/02-numpy.md, _episodes/04-loop.md, _episodes/06-files.md, _episodes/10-defensive.md
I've added suggested image descriptions for the remaining figures listed in Issue #781.
This includes changes to Episodes 2, 4, 6, and 10.
Thank you,
V
=> Episodes 2, 4, 6, 10: Improving image descriptions

_episodes/08-func.md, reference.md
This adds a brief section about variable scope, that defines local variables, to the functions episode. It is related to the discussion in #917.
=> 08-func.md: Add section on variable scope and local variables

_episodes/01-intro.md
<details>
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> Updated explanatory text around multiple variable assignment

_episodes/01-intro.md
This proposes text for introducing what built-in means. It also brings in the `type` function in that context. This relates to #766, #899, and #919. Feedback is welcome.
=> Add text about built-in functions

_episodes/03-matplotlib.md
I think it's a bit better to change the second objective of this episode from "Group several graphs ..." to "Plot a group several graphs ..."
=> Modify the second objective of the episode 03-matplotlib

_episodes/04-lists.md
<details>
I have taken 1 out of the primes list in the heterogeneous lists section because 1 is not a prime number.
\- The Carpentries
</details>
=> Edit lists

_episodes/05-loop.md
This changes a variable name from ```char``` to ```letter``` to avoid possible confusion of learners with previous experience in other programming languages that do have a character data type.
<details>
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If …
=> Avoid the variable name 'char'

_episodes/08-func.md
When we introduce function composition, don't use a concise return value line as the first example. I've written a function that does the exact same thing as the original temperature conversion function, complete with comments. I then compare it to the original function below. These two examples show the learner how functions are generated and why the return line can be used more efficiently.
<details>
Keep in mind that **lesson maintainers are volunteers** and it …
=> Beginner-friendly function composition

_episodes/08-func.md
I think it would be helpful to simplify the intro paragraph to something like: if you want to convert a temperature you could write... if you  wanted to convert two temperatures you could copy the line and change on part, and then show code with 10 copied lines. Now say "Does this happen in your code? how can you avoid this?" 
Then show the function definition image
<details> …
=> show an anti-idiom first

_episodes/05-loop.md, _episodes/12-cmdline.md
<details>
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> minor text changes

_episodes/04-lists.md
The ingredients lists sound like actual mild and hot salsa already. By making more intuitive and informative names, we can model variable naming best practices and make it easier to follow the example. To do that, I edited both the code and the surrounding comments and text.
<details>
respond to your contribution. Although not all contributions can be incorporated into the …
=> Clarify names in salsa example

_episodes/12-cmdline.md, code/arith.py
I think maybe a few clarifications could help this section.
1. The operators `add` and `subtract` maybe should have dashes like the actions in the previous example ==> `--add` and `--subtract`. This is just a matter of form, but may be more intuitive for some students. If so the operators would change in the problem and solution sections.
2. In the problem section the program output shows an expected integer result rather than the float cast used in the solution. The problem expected outputs should show float values to agree with the solution.
3. Giving a hint to the student that the solution may also include multiplication and division could be an incentive to try these operators as well.
Of these, I think (2.) should be changed with the others being optional.
<details> …
=> Arithmetic on the Command Line for 12-cmdline.md suggestions

index.md
=> Fix link to setup page

README.md
This PR updates the maintainers list and adds @noatgnu & @ineelhere to the same.
=> updating maintainers section

episodes/10-defensive.md
The function is first called `get_total_cars`, which fits to the problem description, then `get_total`. This pull request fixes that.
=> Use correct function name

episodes/07-cond.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #1073 
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Ensures that both "numpy" and "data" are available as local variables.
It is unclear what the `data` variable should be at this point in the lesson. The last time that variable was created was during a for loop in the previous episode. It may have been overwritten or erased at this point. If we are running the import again, I reckon it's best to create that variable again as well.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries …
=> Recreate data variable along with numpy import
